"""Added id column with auto-increment

Revision ID: d702975a605e
Revises: 
Create Date: 2024-09-09 06:22:19.735203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd702975a605e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.String(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'phone',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
